#!/bin/sh

# Command to force only network by AT commands
# sudo -v && sudo sh -c "echo -ne 'AT+COPS=1,1,"INDOSAT",2\r\n' > /dev/ttyUSB2";

AT_COMMAND=AT+COPS
AUTOMATIC_OR_MANUAL=1
SHORT_OR_LONG=1
NAME=INDOSAT
NETWORK=2
DEVICE=/dev/ttyUSB2

if [ ! -z "$1" ]; then
    NETWORK=$1
fi

if [ ! -z "$2" ]; then
    NAME=$2
fi

if [ ! -z "$3" ]; then
    DEVICE=$3
fi

MESSAGE="echo -ne '${AT_COMMAND}=${AUTOMATIC_OR_MANUAL},${SHORT_OR_LONG},\"${NAME}\",${NETWORK}\r\n' > ${DEVICE}";
echo $MESSAGE && sudo -v && sudo sh -c "${MESSAGE}";
