#!/bin/sh

# Command for creating high quality gif using ffmpeg

# Refference from https://ffmpeg.org/ffmpeg-filters.html
#
# ffmpeg -i input.mkv -vf palettegen palette.png
# ffmpeg -i input.mkv -i palette.png -lavfi paletteuse output.gif
#
# Modified by Panji Kusuma., <epanji at gmail dot com>

WIDTH=480
PALETTE=`mktemp -u`.png
if [ ! -z "$3" ]; then
    WIDTH=$3
fi

FILTERS="fps=10, scale=$WIDTH:-1:flags=lanczos"

ffmpeg -v warning -i $1 -vf "$FILTERS, palettegen" -updatefirst 1 -y $PALETTE && \
ffmpeg -v warning -i $1 -i $PALETTE -lavfi "$FILTERS [video]; [video][1:v] paletteuse" -y $2 && \
rm $PALETTE
